Feature/controller update controller
TECH-Rubicone/redux-saga-controller pull request #18
Opened 2020-11-21 19:34 UTC by zanusilker

2020-11-22 21:39 UTC, zanusilker commented
![image](https://user-images.githubusercontent.com/16426586/99917891-0029b680-2d1c-11eb-958f-2b6471253572.png)

2020-11-23 11:37 UTC, sajera commented on example/store.ts
> +    controller: controllerReducer,
as addition ability we may implement method to provide custom redux name for example
```javascript

...controllerReducerCustom('myCustomReducrName'); //  => { [name]:  controllerReducer }
```

2020-11-23 11:43 UTC, sajera commented on src/controller.ts
> +    this.DEBUG = isBoolean(DEBUG) ? DEBUG : false;
use local storage to enable debug mode

2020-11-23 12:03 UTC, sajera requested changes

2020-11-23 12:03 UTC, sajera commented on src/utils.ts
> +  if (!counter[prefix]) {
should generate not only unique but new one each time

2020-11-24 16:34 UTC, merged